# Generated by Django 2.0.7 on 2018-07-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_value', models.CharField(max_length=255)),
                ('num_type', models.CharField(max_length=255)),
                ('parent_textarea_id', models.CharField(max_length=255)),
            ],
        ),
    ]
